version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    ports:
      - '3000:3000'
    networks:
      - backend

networks:
  backend:
    driver: bridge